---
title: "Basic introduction to common tools"
---

## RNA-seq

* TODO

## DNAm

* [Measuring cell-type specific differential methylation in human brain tissue](https://genomebiology.biomedcentral.com/articles/10.1186/gb-2013-14-8-r94)
* [From promises to practical strategies in epigenetic epidemiology](https://www.nature.com/articles/nrg3405)
* [A data-driven approach to preprocessing Illumina 450K methylation array data](https://bmcgenomics.biomedcentral.com/articles/10.1186/1471-2164-14-293)
* [Epigenetic memory in induced pluripotent stem cells](https://www.nature.com/articles/nature09342)
* [The human colon cancer methylome shows similar hypo- and hypermethylation at conserved tissue-specific CpG island shores](https://www.nature.com/articles/ng.298)
* [Bump hunting to identify differentially methylated regions in epigenetic epidemiology studies](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3304533/)
* [Analysing and interpreting DNA methylation data](https://www.nature.com/articles/nrg3273)
* [DNA methylation: roles in mammalian development](https://www.nature.com/articles/nrg3354)
* [The Key Role of Epigenetics in Human Disease Prevention and Mitigation](https://www.nejm.org/doi/full/10.1056/NEJMra1402513)
* [Charting a dynamic DNA methylation landscape of the human genome](https://www.nature.com/articles/nature12433)
* [Global Epigenomic Reconfiguration During Mammalian Brain Development](https://science.sciencemag.org/content/341/6146/1237905.long)
* [Divergent neuronal DNA methylation patterns across human cortical development: Critical periods and a unique role of CpH methylation](https://www.biorxiv.org/content/10.1101/428391v2.full)

## `bash` and `linux`

* [Linux essentials](https://faculty.ucr.edu/~tgirke/Documents/UNIX/linux_manual.html)
* [The Unix Workbench](https://seankross.com/the-unix-workbench/) by [Sean Kross](http://seankross.com).
* [Rsync (Remote Sync): 10 Practical Examples of Rsync Command in Linux](https://www.tecmint.com/rsync-local-remote-file-synchronization-commands/).
* [Linux file permissions](http://windowsbulletin.com/filepermissions/).
* [How To Use Linux Screen -- website 1](https://linuxize.com/post/how-to-use-linux-screen/) and [How To Use Linux Screen -- website 2](https://www.rackaid.com/blog/linux-screen-tutorial-and-how-to/).

## `R`

* Download and install [R from CRAN](https://cran.r-project.org/).
* [R 101](http://research.libd.org/rstatsclub/post/r_101/#.XXfwU5NKi50) LIBD rstats blog post by [Carrie Wright](https://carriewright11.github.io/).
* [Download RStudio Desktop](https://www.rstudio.com/products/rstudio/#Desktop).
* [Using the RStudio Terminal](https://support.rstudio.com/hc/en-us/articles/115010737148-Using-the-RStudio-Terminal).
* RStudio [cheatsheets](https://www.rstudio.com/resources/cheatsheets/) for many things including regular expressions, `purrr` for functional programming, etc.
* [Building Tidy Tools workshop materials](https://rstd.io/tidytools19) by Charlotte Wickham and Hadley Wickham for the rstudio 2019 conference. Materials from other workshops is available [here](https://blog.rstudio.com/2019/02/06/rstudio-conf-2019-workshops/).
* [R Markdown documentation website](https://rmarkdown.rstudio.com/docs/) announced by [Alison Hill](https://twitter.com/apreshill/status/1171290891157307392?s=20).
* [Cookbook for R graphs](http://www.cookbook-r.com/Graphs/) with useful `ggplot2` code.
* [Updating R](http://lcolladotor.github.io/2017/05/04/updating-r/#.XXf3hZNKi50) blog post by Leo.
* Tutorial for [building R websites](http://www.emilyzabor.com/tutorials/rmarkdown_websites_tutorial.html) by [Emily C Zabor](http://www.emilyzabor.com/) which is how this website was made. More on R Markdown websites [here](https://bookdown.org/yihui/rmarkdown/rmarkdown-site.html).

## `python`

* TODO
