---
title: "Where to eat near LIBD"
---


* **North East Market**: it's on [2101 E Monument St](https://goo.gl/maps/Cy7K5LJ3pZx9p3Mr5) which is just a few minutes away walking. You can find a lot of variety there including a Korean stall along the south wall. That stall is pay-by-weight and lots of the dishes are delicious.
* School of Public Health 9th floor salad bar **[Garden Plate](https://www.yelp.com/biz/garden-plate-baltimore)**: walk two blocks north to [615 N Wolfe St](https://goo.gl/maps/E5yJzcK4EA4mdTB89) or K 3-4 on the [Hopkins East Baltimore Campus map](https://www.hopkinsmedicine.org/the_johns_hopkins_hospital/_docs/jhi_visitors_guide.pdf), then take an elevator on the south side of the building to the 9th floor. The elevators on the north side don't go all the way up to the 9th floor.
* **[Kabobi](http://www.helmandkabobi.com/)**: Afghan food, really quick for take-out. Popular choices are the lamb or chicken rice bowls, chopped salads, and the veggie rice bowls.
* **Greenhouse**: This is in neighboring Preclinical Teaching Building (PCTB); it's on K2 on the [Hopkins East Baltimore Campus map](https://www.hopkinsmedicine.org/the_johns_hopkins_hospital/_docs/jhi_visitors_guide.pdf). Have someone show the inside way - or go outside and it's just inside the Wolfe/Monument corner entrance. It's a pay-by-weight buffet with salad bar and hot options. Not amazing but great lower cost option, especially if you are going for the lighter weight foods like salad!
* **[Atwater's](https://www.atwatersfood.com/shops/hopkins)**: Good sandwiches, but more expensive for what you get.




## Food trucks

* **Koko** - Korean food on Tuesdays and Fridays. A lab favorite! Favorites are bulgogi (beef) and tofu dishes.
* **Chowhound** - burgers (incl. veggie) on Mondays and ?. GREAT FRIES.
* Other good ones: Greek truck, Kabob/falafel truck in front of Starbucks




## Other

* Food court inside the hospital (good luck finding it!) with Subway, Einstein Bros, and others. It's on G-H 4 on the [Hopkins East Baltimore campus map](https://www.hopkinsmedicine.org/the_johns_hopkins_hospital/_docs/jhi_visitors_guide.pdf). There's a second one at I6 on the same map.
* Dunkin, Subway, and Chinese places along Monument St.
